# Generated by Django 3.0.5 on 2020-07-28 06:39

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', django_mysql.models.JSONField(default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'StudentAttendance_Table',
            },
        ),
    ]
