version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'ATTENDANCE'
      MYSQL_USER: 'dilip'
      MYSQL_PASSWORD: 'dilip'
      MYSQL_ROOT_PASSWORD: 'dilip'
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py test && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Attendance
    ports:
      - '8000:8000'
    depends_on:
      - db
  