# Generated by Django 3.0.5 on 2020-07-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionId', models.AutoField(primary_key=True, serialize=False)),
                ('sectionName', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Section_Table',
            },
        ),
    ]
