# Generated by Django 3.0.5 on 2020-07-29 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20200729_0429'),
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='departmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department', unique=True),
        ),
    ]
