# Generated by Django 3.0.5 on 2020-07-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '__first__'),
        ('section', '0001_initial'),
        ('year', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.Semester')),
                ('subject', models.ManyToManyField(to='subject.Subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='year.Year')),
            ],
            options={
                'db_table': 'Class_Table',
            },
        ),
    ]
