# Generated by Django 3.0.5 on 2020-07-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
